# The lines bellow are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

release:
  draft: true
  replace_existing_draft: true
  header: |
    ## {{ .ProjectName }} v{{ .Tag }}

    ## Images
    * Operator: quay.io/path/to/operator/image:v{{ .Tag }}
    * Bundle: quay.io/path/to/operator/bundle/image:v{{ .Tag }}
    * Catalog: quay.io/path/to/operator/catalog/image:v{{ .Tag }}

    ## Notable changes
    <to be filled with items from changelog below>

  # Set this to true if you want to disable just the artifact upload to the SCM
  skip_upload: true

archives:
  # Archives won't be uploaded, but we can't avoid them to be created.
  # Define the minimum and fastest process.
  - format: binary

changelog:
  # `github`: uses the compare GitHub API, appending the author login to the changelog.
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
