# permissions for end users to edit jobpocremediations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: jobpocremediation-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: job-poc
    app.kubernetes.io/part-of: job-poc
    app.kubernetes.io/managed-by: kustomize
  name: jobpocremediation-editor-role
rules:
- apiGroups:
  - job-poc-remediation.medik8s.io
  resources:
  - jobpocremediations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - job-poc-remediation.medik8s.io
  resources:
  - jobpocremediations/status
  verbs:
  - get
