---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - job-poc-remediation.medik8s.io
  resources:
  - jobpocremediations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - job-poc-remediation.medik8s.io
  resources:
  - jobpocremediations/finalizers
  verbs:
  - update
- apiGroups:
  - job-poc-remediation.medik8s.io
  resources:
  - jobpocremediations/status
  verbs:
  - get
  - patch
  - update
